name: Install cleret
runs:
  using: composite
  steps:
  - shell: bash
    env:
      REPO: ${{ github.action_repository }}
      RELEASE: ${{ github.action_ref }}
      GH_TOKEN: ${{ github.token }}
    run: |
      BINDIR=$HOME/.local/bin
      mkdir -p "$BINDIR"
      grep -q "$BINDIR" "$GITHUB_PATH" || echo "$BINDIR" >>"$GITHUB_PATH"

      # TODO: change this to be cross-platform, or remove it.
      # Although `gh` should always be present on one of GitHub's runners,
      # it typically isn't when testing a workflow locally with `act`.
      type gh || { sudo apt-get update && sudo apt-get install -y gh; }

      PLATFORM=$(uname -s)-$(uname -m)
      DOWNLOAD=$(mktemp -d)
      trap 'chmod -R u+w "$DOWNLOAD"; rm -rf "$DOWNLOAD"' EXIT

      if gh release view -R "$REPO" "$RELEASE" --json '' >/dev/null
      then
        echo "Downloading asset from release $RELEASE"
        gh release download -R "$REPO" "$RELEASE" -D "$DOWNLOAD" -p "*-$PLATFORM*"
      else
        echo "Downloading artifact from commit $RELEASE"
        RUNID=$(gh run list -R "$REPO" -c "$RELEASE" -w 'Nix Build' --json 'databaseId' -q '.[0].databaseId')
        if [[ -z "$RUNID" ]]
        then
          echo >&2 "No run found for commit $RELEASE"
          exit 1
        fi
        gh run download -R "$REPO" "$RUNID" -D "$DOWNLOAD" -p "*-$PLATFORM*"
      fi

      tar -xf "$(find "$DOWNLOAD" -type f)" -C "$DOWNLOAD"
      install "$(find "$DOWNLOAD" -path '*/bin/cleret')" "$BINDIR"
