name: Haskell CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc: ['9.6.7', '9.8.4', '9.10.2', '9.12.2']
      fail-fast: false

    name: Build with GHC ${{ matrix.ghc }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Haskell setup
      uses: haskell-actions/setup@main
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Configure
      run: |
        cabal update
        cabal configure --enable-tests --enable-benchmarks

    - name: Build dependencies
      run: cabal build all --only-dependencies

    - name: Build
      run: cabal build all

    - name: Run tests
      run: cabal test all
