name: Nix Build

on:
  pull_request:
  push:
    branches: ["master", "main"]
    tags: ["*"]
  workflow_dispatch:
    inputs:
      version:
        type: string

permissions:
  contents: read

jobs:
  build:
    name: 'Nix Build: build'

    runs-on: ubuntu-latest

    outputs:
      artifact: ${{ steps.result.outputs.artifact }}

    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Install nix
      uses: cachix/install-nix-action@v31

    - name: Build
      id: build
      run: nix build --accept-flake-config .#static

    - name: Record result
      id: result
      run: |
        derivation=$(nix derivation show ./result | jq -r '(.derivations // .).[].env.name')
        artifact=$derivation-$(uname -s)-$(uname -m)
        products=$(find -L result -type f)
        echo "artifact=$artifact" >>"$GITHUB_OUTPUT"
        echo "products=$products" >>"$GITHUB_OUTPUT"

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.result.outputs.artifact }}
        path: ${{ steps.result.outputs.products }}

  release:
    if: github.ref_type == 'tag' || inputs.version

    name: 'Nix Build: release'

    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ needs.build.outputs.artifact }}
        path: artifact

    - name: Create release content
      id: content
      run: |
        version='${{ github.ref_type == 'tag' && github.ref_name || inputs.version }}'
        release='${{ needs.build.outputs.artifact }}'-$version
        archive=$release.tgz
        mv artifact "$release"
        tar -czf "$archive" "$release"
        notes=$release.md
        cat <<EOF >"$notes"
        See [CHANGELOG.md](${{ github.server_url }}/${{ github.repository }}/blob/main/CHANGELOG.md)
        EOF
        echo "version=$version" >>"$GITHUB_OUTPUT"
        echo "archive=$archive" >>"$GITHUB_OUTPUT"
        echo "notes=$notes" >>"$GITHUB_OUTPUT"

    - name: Create release
      run: |
        gh release create \
          '${{ steps.content.outputs.version }}' \
          '${{ steps.content.outputs.archive }}' \
          --notes-file '${{ steps.content.outputs.notes }}' \
          --repo '${{ github.repository }}' \
          --target '${{ github.sha }}' \
          --verify-tag \
          --fail-on-no-commits \
          --draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
